# Generated by Django 4.1.5 on 2023-01-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubrepresentative',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
